# Generated by Django 5.0.1 on 2024-08-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='created_at',
        ),
    ]
